[development]
rpc_host = "localhost"
rpc_port = "9005"
rest_host = "localhost"
rest_port = "9006"
log_level="debug"
server_cert="cert/server.crt"
server_key="cert/server.key"
database_url = "mongodb://mongodb:27017/integration_test" 

[test]
rpc_host = "localhost"
rpc_port = "9005"
rest_host = "localhost"
rest_port = "9006"
database_url = "mongodb://mongodb:27017/integration_test" 
log_level="debug"
server_cert="/root/cert/server.crt"
server_key="/root/cert/server.key"

[production]
rpc_host = "localhost"
rpc_port = "9005"
rest_host = "localhost"
rest_port = "9006"
database_url = "mongodb://mongodb:27017/integration_test"
log_level="debug"
server_cert="cert/server.crt"
server_key="cert/server.key"

