[development]
rpc_host = "localhost"
rpc_port = "9003"
rest_host = "localhost"
rest_port = "9004"
log_level="debug"
server_cert="cert/server.crt"
server_key="cert/server.key"
database_url = "mongodb://localhost:27018/integration_test" 

[test]
rpc_host = "localhost"
rpc_port = "9003"
rest_host = "localhost"
rest_port = "9004"
database_url = "mongodb://localhost:27018/integration_test" 
log_level="debug"
server_cert="cert/server.crt"
server_key="cert/server.key"

[production]
rpc_host = "localhost"
rpc_port = "9003"
rest_host = "localhost"
rest_port = "9004"
database_url = "mongodb://localhost:27018/integration_test"
log_level="debug"
server_cert="cert/server.crt"
server_key="cert/server.key"

