// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_logger_request.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	get_logger_request.proto
	logger.proto
	logger_response.proto
	logger_responses.proto
	logger_service.proto

It has these top-level messages:
	GetLoggerRequest
	LoggerMessage
	LoggerResponse
	LoggerResponsesMessage
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetLoggerRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Level       string `protobuf:"bytes,2,opt,name=Level" json:"Level,omitempty"`
}

func (m *GetLoggerRequest) Reset()                    { *m = GetLoggerRequest{} }
func (m *GetLoggerRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLoggerRequest) ProtoMessage()               {}
func (*GetLoggerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetLoggerRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *GetLoggerRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func init() {
	proto.RegisterType((*GetLoggerRequest)(nil), "pb.GetLoggerRequest")
}

func init() { proto.RegisterFile("get_logger_request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4f, 0x2d, 0x89,
	0xcf, 0xc9, 0x4f, 0x4f, 0x4f, 0x2d, 0x8a, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2, 0xe2, 0x12, 0x70, 0x4f, 0x2d, 0xf1,
	0x01, 0x4b, 0x07, 0x41, 0x64, 0x85, 0x14, 0xb8, 0xb8, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53,
	0xfd, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x44, 0xb8,
	0x58, 0x7d, 0x52, 0xcb, 0x52, 0x73, 0x24, 0x98, 0xc0, 0x72, 0x10, 0x4e, 0x12, 0x1b, 0xd8, 0x58,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x72, 0xdc, 0xfb, 0x72, 0x00, 0x00, 0x00,
}
